### PR TITLE
Handler base class

### PR DESCRIPTION
**Pull request by kozzztik**
To make SMTP protocol more extensive I added three new handler methods to handle MAIL, RCPT and VRFY commands. 
MAilL and RCPT handlers return special SMTPAddress instanses to correctly handle their options. Also that is possibility for make correct handling of aliases or disctribution lists or collect some information. For example when receiving email for user you can check database if it exists. If so, save on SMTPAddress user information to be used in future on processing stage. 
This is the half of answer on TBD in Proxy handler, how to handle refused recipients. When MAIL command recieved handler must create SMTP session with remote server and send MAIL and RCPT commands directly to remote servers online just when they received, so you wouldn`t receive refused recipients in process_message state. This will be possible with PR #39

From this point handler class have too much methods to work with him as "black box". Its better to make it special well documented class.
During this process I removed backward support of sync/async handler versions. I don`t know why it was done. As I understand PEP-20 this is not good idea. Async version can contain only sync code so there is no need double versioning of methods and handlers.

### CODE REVIEW

**Comment by Mortal** [comment]
As mentioned in #47, it would be nice to be able to respond with a 4xx or 5xx code in handle_RCPT, since it allows the server to avoid the (sometimes expensive) DATA command when it is known ahead of time that the recipient is invalid (or there is some other failure mode).

This is not possible with smtpd, so it is not strictly required in order for aiosmtpd to be an smtpd replacement, but most "real" SMTP servers send the 550 invalid recipient in response to RCPT and not in response to DATA -- just take a look at any Postfix log file or Postfix-generated DSN, and you'll see "550 mailbox unavailable (in response to RCPT)" more often than "(in response to end of DATA)".

**Comment by kozzztik** [comment]
@Mortal, this is already included in this PR. It introduces SMTPException, which you can raise in any handler to provide any error response that you need.

**Comment by kozzztik** [comment]
@warsaw, I strongly prefer to return recipient/sender. I like idea of getting them back in process message as-is, so it makes logic independed of any entity end-user want to operate with. It may be database record or Django ORM object or whatever else. User(developer, how our auditory is called?) can just return in handler wat it wants. Other cases covered by rising exceptions.

**Comment by warsaw** [comment]
I suck at causing conflicts, but now I think I'm mostly done with my own wishlist for 1.0.

**Comment by kozzztik** [comment]
Updated with master.

**Comment by kozzztik** [comment]
Please, think about this PR as aggressive brainstorm idea and place of discussion. Im not expect thatit would be merged. Maybe it would completely changed with review. I just want to provide my vision of how it can be done other way. I splitted part of it to separate PR #52, and also will create separate PR for Proxy class with RCPT and MAIL handlers.
During whis changes I just kept in mind some PEP20 positions:
- Explicit is better than implicit. 
- Complex is better than complicated.
- There should be one-- and preferably only one --obvious way to do it.

Ducktyping with one method if fine enough, but many of them it is very implicit implementation, and jumping over it in protocol to check their versions and presense is complicated. Descending base class is looks like one needed way to implement user handler.
But: 
- Although practicality beats purity.
and ducktyping is obviously practial.
Althrough, that rules, I`m sure, abstract enough to be readed in other way, and changes aggressive bacwards incompatible, so here is many things to be discussed.

**Comment by warsaw** [comment]
I really do appreciate seeing your vision for a richer extension/handler API.  Here are some of my thoughts.

I feel strongly that `handle_*()` methods should be as consistent as possible.  That means they should take the same arguments and return/yield the same results.  The strong advantage of that is that is that once people learn the basic API, there's no guessing and less of a need to look up the documentation.  Since we have session and envelope objects, and we already pass that to `handle_DATA()` I'd like to see how far we can take that.

I think we should allow the handlers to change the return status and state machine of the SMTP class.  For example #47 should be easily doable using the rich handler API, but I don't as much like using exceptions for that.  Causing a 550 return isn't an exceptional case; IOW it's not an error, and I think exceptions should generally be used for exceptional cases, not valid use cases like returning an error code to the client.  I'd prefer either yielding the status or possibly setting it in the session object.

If you look for example in `handle_RCPT()` and how it's used in `SMTP`, it seems more natural to me to pass in the session and envelope, and let `handle_RCPT()` just append to `envelope.rcpt_tos` if it wants to.  Similarly for `handle_MAIL()` and `envelope.mail_from`.  I am leaning toward yielding the return status since that seems the most straightforward API.  We could even include a little enum for commonly yielded status codes and messages.

To me, that gives us nice clean simple API.  Whether we provide a base handler class or not is a secondary discussion, which we can have once we've nailed down the rest.  I would be inclined not to *require* derivation from the base class, but to provide one for convenience.  I think all that would mean would be to remove the `assert` from the `SMTP` constructor.  (It shouldn't be an assertion anyway, since it's more Pythonic to use assertions for situations that should never happen.  If a base class is required, then a `ValueError` or `TypeError` would be more appropriate to raise.  Still I don't think this has to be required.)

**Comment by kozzztik** [comment]
@warsaw, hah! Just was thinking about same and made a draft for that in #57. If you like it, I can finish it there, and keep this PR talking about ducktyping vs base handler class.

**Comment by warsaw** [comment]
@kozzztik Thanks again for this branch.  It really helped spark some good conversations about the handler API, and it helped solidify my thinking about the use cases.  I think we can close this PR now, but if you feel there's still something missing we need, either reopen this one or open a new PR.  Thanks for making this package so much better!

**Pull request closed without merging**
