### PR TITLE
stream reader read line must be in try catch because of a lost connection

### PR DESCRIPTION
**Pull request by kazimsarikaya**
Dear all,
stream reader's read function is inside a loop. if client connection is closed, future raises a cancellederror like:

```
Traceback (most recent call last):
  File "/Users/kazim/pythonprojects/smtpd/lib/python3.5/site-packages/aiosmtpd/smtp.py", line 197, in _handle_client
    yield from method(arg)
  File "/Users/kazim/pythonprojects/smtpd/lib/python3.5/site-packages/aiosmtpd/smtp.py", line 513, in smtp_DATA
    line = yield from self._reader.readline()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/streams.py", line 482, in readline
    line = yield from self.readuntil(sep)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/streams.py", line 575, in readuntil
    yield from self._wait_for_data('readuntil')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 285, in result
    raise CancelledError
concurrent.futures._base.CancelledError
```

Hence we should use a try catch for CancelledError and cleanup.

### CODE REVIEW

**Comment by warsaw** [comment]
Thanks; can you think of a useful test to boost coverage back to 100%?

**Comment by Mortal** [comment]
I think the solution is incorrect. The CancelledError comes from SMTP.eof_received which [has closed the transport (by returning None)](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.Protocol.eof_received). SMTP.connection_lost is called by the event loop [whenever the connection is lost or closed](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseProtocol.connection_lost), and it is not meant to be called from eof_received, since it will be called soon after eof_received is called (as far as I understand).

I think the right response to CancelledError in `_handle_client` is simply to return.

**Comment by Mortal** [comment]
Hmm, in fact, SMTP.eof_received returns True, so the writer is not closed. I think the right way to handle CancelledError is to call self.transport.close() like smtp_QUIT does.

**Comment by warsaw** [comment]
We really need a unit test for this.

**Comment by warsaw** [comment]
If you can't come up with a unit test, can you describe a scenario to reproduce this on the command line?  With that I might be able to help with the unittest.

**Comment by kazimsarikaya** [comment]
Hi warsaw, I tried to write a kind of test. However the main problem i encountered is how to kill client. I test this error with these steps on command line:
1) start a normal smtp session with: ehlo, mail from, and rcpt to.
2) start data command, and write a few lines. 
3) kill -9 client (not finished data command.) 

inside unit test, i can not find a way to kill the Python SMTP client (with -9).

Best regards.

**Comment by warsaw** [comment]
@kazimsarikaya Thanks!  That might be enough for me to craft a test case.

**Comment by Mortal** [comment]
See [my PR](https://github.com/aio-libs/aiosmtpd/pull/59/files#diff-ce34ff8c12546b28b05a058b083a27ac) for how to reset a connection in a test. I'm not sure if it's the good way of doing it, but it's the best way I could find.

**Comment by kazimsarikaya** [comment]
@Mortal I read your pull request. I didn't find any problem. You test it with tcp reset, hence it also produced cancellederror. I think it is enough for testing.

**Comment by warsaw** [comment]
Using the tip in #59 I have some test cases.  The first test case resets the connection after `DATA` but before the `.\r\n`.  The second two test cases throw in an `EOF` (`\0x4`) during the data content and in the middle of the `MAIL FROM` command.  What these last two tell me is that the `readline()` also has to be protected by a `ConnectionResetError` catch.

Much more difficult is to cause an `asyncio.CancelledError` in `_handle_client()`'s `readline()` call.  Because that call essentially blocks until the `\r\n` is read, I can't seem to cause that exception by resetting the client's connection.  But I *can* cause a `ConnectResetError` so an `except` clause that handles both exceptions is a moderately effective code coverage test case.  Unless anyone has a better idea, it'll have to do.

I'll have a PR up as soon as I can address a few other issues.  This new PR will also include some nicer debugging hooks for the test suite.  Then I think we'll have to figure out how to land all of these branches since they seem to touch very similar bits of the code.

**Comment by warsaw** [comment]
Thanks for the contribution!   I am closing this PR in favor of #73

**Pull request closed without merging**
