### PR TITLE
Add Wayne's key fingerprint

### PR DESCRIPTION
**Pull request by waynew**
## What do these changes do?

Add my key fingerprint to the docs

### CODE REVIEW

**Comment by waynew** [comment]
You can find my key on keyserver.ubuntu.com, and you can also find it on my web page at https://waynewerner.com/about_me

**Comment by waynew** [comment]
Also realized I hadn't setup my git to use this signing key :joy: now it is :+1: (also FYI @pepoluan I just noticed that your signing key expires next month)

**Comment by pepoluan** [comment]
> Also realized I hadn't setup my git to use this signing key 😂 now it is 👍 (also FYI @pepoluan I just noticed that your signing key expires next month)

Ack! Did not notice that ... okay I need to do some key maint on my part as well :D

**Comment by pepoluan** [comment]
Ugh my mind is still a bit foggy due to influenza ... I'm folding up your PR into mine because I also had created a new key.

**Comment by waynew** [comment]
All good :+1: I've had a nasty mostly-nighttime cough myself the last few days so I get that :joy:

**Pull request closed without merging**
