### PR TITLE
Additional handlers (one more variant)

### PR DESCRIPTION
**Pull request by kozzztik**
Thats new variant of how handlers on RCPT and MAIL can be done. That is also adds right Proxy handler implementation. Its a draft so tests wouldn`t pass.

Main problem in #41 I tried to avoid was that I want to make user add custom recipient entities without any additional magic. Thats why in #41 handlers return entities, and they raised special exceptions to return custom response codes.
Here is another way: return status strings as usual, but if handler method is present it is up to method to correctly add entity on envelope.
Thats in addition to #55.

### CODE REVIEW

**Comment by warsaw** [comment]
Other than the obvious bug (`handle_MAIL()` being called in `smtp_RCPT()`) this is getting pretty close.  Implicit in this branch is the fact that `handle_*()` methods will not all take the same argument.  For example, `handle_MAIL()` takes an envelope, the address, and the mail options, but the session is not passed at all.

I understand why you want to pass `address` into the `handle_MAIL()` method; you don't want to have to duplicate all the work that `smtp_MAIL()` does to calculate and verify the address, and that's reasonable.  It still makes the handler APIs inconsistent.

Maybe there's no good way to get around that.  I've thought of several other alternatives but I'm not sure I like any of them any better (e.g. create another object called `Arguments` that lives only as long as the current command).  I think I'd be okay with this approach if every handler took the session, the envelope, and a variable number of additional positional arguments.  So `handle_MAIL(self, session, envelope, address, mail_options)`.

I agree with your decisions on this branch to require that the handler method set `envelope.mail_from` and `envelope.mail_options` if the method exists, and that the handler method would always return the status if the method exists.  I also think all `handle()` methods should be coroutines.  (I'll note that your `handle_RSET() violates both of these currently).

What do you think about that?  I think I'm going to modify my hooks branch to do that and we'll see if that alleviates the concerns that we had about that branch.

**Comment by warsaw** [comment]
A couple of other comments about your branch:

* `_set_rset_state()` should not be calling `handle_RSET()`.  Instead, `smtp_RSET()` should do that.
* I think the `client` attribute should be set on the session, not on the envelope.  (You can't do that yet because you don't pass the session into the handler methods)

**Comment by Mortal** [comment]
I assume the intention of this PR is to avoid having a BaseHandler in aiosmtpd altogether -- is that so?

If there is no BaseHandler, there is no way for users to implement a handler that extends (rather than overrides) the default behavior of aiosmtpd.SMTP. Since the default behaviors for handle_MAIL and handle_RCPT proposed in this PR are very simple, it would be acceptable for a handler in user code to copy over the behavior instead of calling `super().handle_*` on the base class, assuming the default behavior defined in aiosmtpd.SMTP does not change.

I'm not sure if this is enough concern to warrant having an optional BaseHandler in aiosmtpd.

**Comment by warsaw** [comment]
Two other thoughts:  I think handler hooks need a reference to the SMTP class so they can call `.push()` on it (this would allow handler to implement additional ESTMP command for example).  Also, I would like to deprecate `SMTP.rset_hook()` and `SMTP.ehlo_hook()` since both should be implementable via handlers.  That's a little problematic though so I might just silently deprecate them.

**Comment by warsaw** [comment]
@Mortal avoiding the need for a base handler is one of the motivations, but not the only one.  It's definitely intended that for more complicated customizations, clients can override `SMTP.smtp_*()` methods and I've used that exactly for extending.  What's problematic about that is having those overridden methods define different statuses, so that's another thing that the handler methods should be able to do.

(I thought about ways that overidden methods could do that, but they were just too complicated if we wanted to maintain backward compatibility with earlier versions of aiosmtpd.)

**Comment by warsaw** [comment]
Oh, I think I know a (mostly) backward compatible way to deprecate `ehlo_hook` and `rset_hook`

**Comment by kozzztik** [comment]
@warsaw, I think to provide more information to handlers we can link session, protocol and envelope togther by additional link fields on that entities, but I don`t like idea for handlers to push something in protocol manually. If you want to extend protocol with new behavior (even additional entry in EHLO response), you must subclass protocol and ehlo hook method on protocol it was right place to put something there. If you change protocol, change protocol entity. If you change only behavior inside of protocol constraints - you should use handler. So, IMHO, we should keep ehlo hook on protocol, and also add EHLO hook on handler too, so handler will have ability to discard connections on HELO/EHLO stage by peer IP, hostname and etc. To do that it must be possible to access to protocol.close() from handler. It can be added by session.protocol field.

> I think the client attribute should be set on the session, not on the envelope. (You can't do that yet because you don't pass the session into the handler methods)
Agree. I will wait #55 to do that.
> set_rset_state() should not be calling handle_RSET(). Instead, smtp_RSET() should do that.

My idea here was to use something to detect closing of session/envelope, and I used RSET for that. But it is little bit confusing. May be I should just add close() method to session/envelope, so they can explicitly handle their end of life and do clean up if they need.

**Comment by warsaw** [comment]
@kozzztik I think this PR is obsolete with all the recent changes to the API.  Since also there are conflicts, I'm going to close this, but if there's still useful changes in here that you want to see please either reopen and resolve or open a new PR.

I'm highly inclined to defer any more changes until after 1.0 due to the upcoming Pycon.

**Pull request closed without merging**
