### PR TITLE
Simple AUTH PLAIN implementation

### PR DESCRIPTION
**Pull request by athoune**
Here is a naive implementation of AUTH PLAIN.

The auth method, as an argument, is not pythonic enough.

### CODE REVIEW

**Comment by warsaw** [comment]
Hi, thanks for the contribution.  I have a few comments about the code style, but before we get to that, let's talk about [RFC 4954](http://www.faqs.org/rfcs/rfc4954.html).  My understanding based on section 4 is that the initial response is optional.  IOW, the client could sent `AUTH PLAIN` with no initial-response. If this is not present, then a `334 ` challenge is returned (note that the space after the code is required), in response to which the client should then send the response, or `*`.  If a `*` is sent by the client, then the server must reject the `AUTH` command with a `501` response.

If we support any `AUTH` commands, then I think we need to be compliant with RFC 4954 and accept `AUTH` both with and without the initial response.

FWIW, see this patchset which added this functionality to Python's `smtplib.py` stdlib module: https://hg.python.org/cpython/rev/d13263ecf0c6

**Comment by athoune** [comment]
Sure, I was to hurry to implement the challenge/response. I'll fix that, and watch your patchset.

The exception for bas64 trouble is also specified in the RFC.

My next challenge is an option to implement "530 5.7.0  Authentication required"

**Comment by athoune** [comment]
Here is more complete implementation, with challenge, cancel and null.

**Comment by warsaw** [comment]
Can you please rebase/merge master and resolve conflicts?

**Comment by athoune** [comment]
rebase done.

**Comment by warsaw** [comment]
Apologies.  Can you please rebase again and fix the failing CI?

**Comment by athoune** [comment]
hum, there is some troubles with your ssl code :
```
test_failed_handshake (aiosmtpd.tests.test_starttls.TestStartTLS) ... ERROR:asyncio:Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.4/asyncio/selector_events.py", line 670, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.4/asyncio/sslproto.py", line 492, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
AttributeError: 'NoneType' object has no attribute 'feed_ssldata'
```

**Comment by athoune** [comment]
Tests are OK :
```
# nose2  aiosmtpd.tests.test_smtp.TestSMTP
........................................................
----------------------------------------------------------------------
Ran 56 tests in 1.929s

OK
```

**Comment by athoune** [comment]
Hummm, the SSL error only happens with Python 3.4

**Comment by shantanugoel** [comment]
Is this still being pursued?

**Comment by warsaw** [comment]
As with #66 I am deferring AUTH until after 1.0 since we're running out of time before Pycon.  Are you still interested in pursing this work?  I'd like to consolidate these two branches if possible.

**Comment by waynew** [comment]
Hey @athoune! It's been a while since you've worked on this - and quite a while since that pycon :)

Are you interested in completing this? I'd love to have AUTH working in aiosmtpd! If not, just let me know so we can let people know that AUTH is up for grabs!

**Comment by pepoluan** [comment]
Shouldn't we close this since #66 is said to be containing changes of #10 ?

**Comment by pepoluan** [comment]
This has been superseded by #66, and that one has been superseded by #192. So I'm closing this now.

**Pull request closed without merging**
