### PR TITLE
Add docstring to Controller, explaining dual-stack binding.

### LINKED ISSUE #140: How to bind all interfaces dual-stack?
I wish to write a server application that binds to all interfaces in a dual-stack IPv4/IPv6 environment.

I thought the example server would be doing that, as it appears to bind to '::0'. In other applications, like CherryPy, binding to that address makes the server available on all interfaces, IPv4 and IPv6, but in aiosmtpd, the server is only reachable on IPv6. As a result, when the application moves to an environment that only supports IPv4 (looking at you, Docker), the application is unreachable.

Reading up on the [docs for create_server](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.create_server), I see that passing a `None` value for the host should bind to all interfaces on both stacks, and indeed, that's the behavior I see.

But aiosmtpd doesn't allow passing `None` due to the the [localhost default behavior](https://github.com/aio-libs/aiosmtpd/blob/23b743be942ffd37f9c051c1f6efe0108ffd456d/aiosmtpd/controller.py#L14).

I did find one interface that worked, but I'm not happy with it:

```
	cont = controller.Controller(proxy, port=8025)
	# no really, I want all interfaces
	cont.hostname = None
	cont.start()
```

### PR DESCRIPTION
**Pull request by jaraco**
Also updates example to use dual-stack binding. Fixes #140.

### CODE REVIEW

**Comment by Mortal** [comment]
I'd suggest adding a similar text in `aiosmtpd/docs/controller.rst` as well, since that is where I would expect users to find info on the `Controller`.

**Comment by warsaw** [comment]
Agreed w/ @Mortal - also Travis failed.  Is it possible they don't support IPv6?

**Comment by jaraco** [comment]
I have recently encountered issues in Travis. Since November, they have [broken IPv6 support](https://github.com/travis-ci/travis-ci/issues/8711), which is worse than not supporting it at all. I'm fairly certain that the test failures are due to that regression and not my changes, as I only changed the examples and only a docstring in the production lib.

**Comment by jaraco** [comment]
In this latest commit, I've amended the documentation in the docs/ directory. And to help others like myself who might have expected to find the docs in the source, I added a reference to the docs.

**Comment by waynew** [comment]
I'm not super familiar with the term "dual stack" - that refers to IPv6+IPv4 right? Is this a common enough term for the expected audience, or would it be helpful to add something to the effect of  `... dual stack (both IPv6 and IPv4 at the same time) ...`?

It looks like a cursory search would give that same sort of information, if context isn't enough.

**Comment by jaraco** [comment]
Good point. I added a link to the Wikipedia entry to give readers easy access to necessary context.

**Comment by waynew** [comment]
@jaraco It looks like there's a workaround for travis - If the other PR doesn't add it, can you try the fix I posted here? https://github.com/aio-libs/aiosmtpd/pull/143#issuecomment-395967165

**Comment by jaraco** [comment]
Okay - IPv6 disabled in Travis and tests pass now.

**Comment by warsaw** [comment]
@waynew Cool, thanks for reviewing this!  I'll hit the green merge button, but in the future, do you need some additional permissions to do merges?

**Comment by waynew** [comment]
@warsaw yeah, looks like it if you'd like me to be able to press the green merge button :)

**Comment by warsaw** [comment]
@waynew I'v added you as a collaborator.  Not sure if it has enough perms to push the button, so give it a try and get back to me!

**Comment by waynew** [comment]
@warsaw looks like that does it! Thanks!

**Pull request merged**
