### PR TITLE
Test Python 3.9 with Travis CI

### PR DESCRIPTION
**Pull request by hannob**
## What do these changes do?

Enable Python version 3.9 in the CI.

## Are there changes in behavior for the user?

No

### CODE REVIEW

**Review by waynew — APPROVED** [review]
Yes, please!

We may need to start looking into migrating from Travis - I know they've changed their pricing/OS tier 🤔

**Comment by pepoluan** [comment]
I'm all for this!

`py39` testing is part of my huge PR about conversion to pytest, but I'm okay with merging this r.n.

Also: The Travis CI build failure is the infamous intermittent coverage fail with sslcontext suddenly gone None; usually a retriggering of Travis CI will pass.

LGTM!

**Review by pepoluan — APPROVED** [review]

**Comment by pepoluan** [comment]
> We may need to start looking into migrating from Travis - I know they've changed their pricing/OS tier 🤔

Huh, you're [not kidding.](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)

Can we change Travis to do the build "on-demand"? That is, only performing build tests when, say, someone committed with "#Travis" in their commit message, or someone commented with "#Travis" in the PR? That way we can stay under Travis' "1000 free minutes" allocation without needing to request for "additional minutes".

**Comment by pepoluan** [comment]
Let my try closing & reopening this PR so it can (hopefully) pass the Travis CI build test.

**Comment by pepoluan** [comment]
Reopening to retrigger Travis CI; hopefully the hair-pulling `246->255, 255` coverage failure does not happen this time...

**Comment by pepoluan** [comment]
Previously, it failed on `py36`. Now, `py36` passes ... but it failed on `pypy3` -_-

I'd say we just merge it anyways. This intermittent coverage failure is perplexing and I haven't found a satisfactory solution.

**Pull request merged**
