### PR TITLE
HELP refactoring

### PR DESCRIPTION
**Pull request by kozzztik**
Extending protocol with new command I found that it is hard to add it to HELP response. Here is idea of refactoring to make it easier.

### CODE REVIEW

**Comment by warsaw** [comment]
I agree that extending `HELP` is probably not very convenient, but I'd like to avoid adding a new `hook` method given that we were already able to deprecate `ehlo_hook()` and `rset_hook()`.

I'd like to defer this past 1.0 if that's okay with you.  For now, although it is not really convenient, this can still be done by overriding `SMTP.smtp_HELP()`.

**Comment by kozzztik** [comment]
AS I wrote before, I not agree with deprecating ehlo_hook. I think it is fine. If I introduce new command, that is a part of protocol, not handler. If I want to add it and distribute new version to other developers, each of them will need add ehlo handler to declare its support. If I add it to ehlo_hook, its enough to change protocol class to my new one, and everything will work.
If you still want to deprecate it, let me know and I will refactor this PR with it.

**Comment by warsaw** [comment]
Let's separate out the deprecation of `ehlo_hook` from the other bits about HELP refactoring.  My main question was whether we needed three ways of extended SMTP, by overriding or adding `smtp_*()` commands, by handler methods, and by ad-hoc `*_hook()` methods.  I am hoping that we can get by with just the two non-deprecated extension mechanisms.  I understand what you're saying about protocol vs. handler though.

As for refactoring HELP, I like your general approach.  I wonder if we can find a way not to need the `help_hook()` method, and to not rely on the docstrings for the syntax.  (Docstrings are a precious resource so once we make it part of the API, we can't reuse it for anything else later.)

Instead of using a docstring, what do you think about adding a decorator, e.g. `@help('250 Syntax: FOO')` which would put that string on, say the `__syntax__` method of the function?  `@help()` could take an optional keyword argument `extended=False` which, when True would add the extended string to it.

As for `supported_commands` we can mostly introspect that by looking for `smtp_*()` methods that include a `__syntax__` attribute.  The tricky part is the optional support for `STARTTLS`.  We could potentially support that with another keyword argument `when`, which would default to None.  If it's not None, then it would either be an attribute to check, or a predicate function (but I don't want to use lambdas here).  Here are a few examples to show you what I mean:

```python
    @asyncio.coroutine
    @syntax('250 Syntax: HELO hostname')
    def smtp_HELO(self, hostname):
        # ...

    @asyncio.coroutine
    @syntax('250 Syntax: MAIL FROM: <address>', extended=True)
    def smtp_MAIL(self, arg):
        # ...

    @asyncio.coroutine
    @syntax('250 Syntax: STARTTLS', when='tls_context')
    def smtp_STARTTLS(self, arg):
        # ...
```

What do you think?

**Comment by kozzztik** [comment]
Decorator is perfect idea! Lets finish with #4 (sure it will conflict, and I getting crazy to update that old PR)and I will work on it.

**Comment by kozzztik** [comment]
Merged with master and updated with review feedback.

**Comment by warsaw** [comment]
Thanks for the updates, it looks nice this way doesn't it?!   I still want to defer past 1.0 because I want to release 1.0 on Monday, we're already in RC, and I need to finish my talk :)

**Comment by kozzztik** [comment]
That looks really much better. That is good practice of intoducing such features thanks for your decorator idea. May be it is good idea to include it in 1.0 and pycon? This feature looks like good illustration on why aiosmtpd better then stdlib smtpd. That is incredibly new not only of asyncio, but new ideas. But I don`t know how you talk would look like, may be you done some code illustrations and pycon al almost came. I have no problems to defer it, sure it wouldn`t intersect with other PRs.

**Comment by warsaw** [comment]
Conflicts resolved, implementation cleaned up, and additional tweaks in #119

**Pull request closed without merging**
