### PR TITLE
Enable Travis-CI, disable Gitlab-CI

### LINKED ISSUE #1: Need Travis-CI integration
The old GitLab `.gitlab-ci.yml` is no longer appropriate since the move to GitHub.  We need a .travis-ci.yml file for Travis integration.

### PR DESCRIPTION
**Pull request by warsaw**
Closes #1

### CODE REVIEW

**Comment by jettify** [comment]
Name of the file should be `.travis.yml`

**Comment by warsaw** [comment]
Odd, it passes with Python 3.6 but not 3.5 or 3.4.  Could this be related to https://github.com/python/asyncio/pull/366

**Comment by popravich** [comment]
Actually tox runs only python3.4 for all Travis environments.
So either tox.ini should be fixed or `python -m nose2` command should be run explicitly instead of `tox`

**Comment by asvetlov** [comment]
@popravich is right
@warsaw what do you prefer: setting up travis box for running tox properly or getting rid of tox for travis  runs?

**Comment by popravich** [comment]
I would recommend 'getting rid of tox for travis' way -- it would allow multiple simultaneous travis jobs (to test with different python versions).

**Comment by warsaw** [comment]
@popravich Why does tox only run on Python 3.4 on Travis environment?  I know I've had trouble with Travis before on a project where we needed to run exactly on a specific Ubuntu version, with packages only from the archive.  In that case, we ended up using a specifically-tailored docker image.  We probably don't want that here though.

One other thing that tox is useful for is making sure the right test dependencies are installed in tox's venvs.  I.e. it runs setup.py *and* installs additional `deps` from tox.ini.

I don't want to change tox.ini because that's primarily useful on developer machines.   It's probably better to pip install the dependencies and manually run the various envlist commands in the .travis.yml.  Let me give this a try.

@popravich @asvetlov Thanks!

**Comment by popravich** [comment]
You can check the log output -- https://travis-ci.org/aio-libs/aiosmtpd/jobs/144861843
in the tracebacks you'll see tox using python3.4 from `/opt/python3.4.2/`.
And tox only run `py34-{cov,nocov}` environments

**Comment by warsaw** [comment]
I'm closing this and opening a new PR

**Pull request closed without merging**
