### PR TITLE
[RFC] smtp.rst example -- custom handler instead of subclassing?

### PR DESCRIPTION
**Pull request by Mortal**
I think aiosmtpd docs should put more weight on using the default SMTP class and just providing a custom handler class.

Currently smtp.rst introduces a subclass of SMTP that implements smtp_PING and smtp_RSET. Handlers are mentioned, but the example only uses a custom handler as a way of storing a "RSET counter" instead of actually show-casing "handle_RSET".

A first step (implemented in this PR) is to implement "handle_RSET" instead of "smtp_RSET". The prose still needs to be reworked to explain the "handle_"+command pattern for handler method names.

What do you think @warsaw and @kozzztik?

### CODE REVIEW

**Comment by warsaw** [comment]
@Mortal Thanks for starting a conversation about improving the documentation.  I do think we should document both handlers and subclassing, but that we should emphasize (or at least introduce) handlers first.  `smtp.rst` is intended to document the `SMTP` class.  We do have a `handlers.rst` file but that mostly documents the existing handlers.

What do you think about refactoring some of the high level options for extending and customizing aiosmtpd into a separate `customizing.rst` file or some such?

**Comment by Mortal** [comment]
I can give this a shot. Another brief question popped up: Is the Controller intended only for testing? Right now the doc page describing the Controller is called "The testing framework". I was hoping I could use the Controller as the primary backend in my mail forwarder.

If the Controller is indeed meant to be used in what you might call "small-scale production environments" then I'll also try to incorporate that.

**Comment by warsaw** [comment]
The `Controller` really grew out of testing work I'd done in other projects, but I think you're right that it's really not directly tied to testing environments.  For example in Mailman 3, we use a controller for the production LMTP process.  it's a convenient way to run any SMTP instance in a subthread which can be independently started and stopped.   So yes, the documentation should probably be updated with that in mind.  Thanks!

**Comment by Mortal** [comment]
I took a first shot at it @warsaw. I don't think it's quite there yet:

* Command line options should go somewhere other than the new "Getting started" page
* The "Enable SMTPUTF8" section in "Getting started" also seems a bit out of place
* Handler documentation is split between "Getting started", "SMTP class: Handler hooks" and "Handlers" -- should probably be closer together somehow

Any comments so far?

**Comment by kozzztik** [comment]
Hi!
I dreaming of have enough time to finish Proxy handler to correctly use MAIL and RCPT commands and creating connection over Envelope object. Thats one of reasons why all that things was introduced. When that be done, that class will be good example of how you can use handlers (also it will open one more question about closing envelope objects). You can see start of it here #57, I just need to split it and finish.

I also have my own extention of SMTP for my project needs. It introduces new DATA-like command to send additional technical information with email. I wasn`t sure someone else needs it, as thats what email headers exist for. But I hate using headers to transmit technical data and it is too big to use headers. I can contribute it as complete example of SMTP extention (and I will get rid of more patch code in py project with it, dream of remove all of it). It may be useful as it opens some extention questions itself, that is shown in #69. 

If someone will well document all of it (someone who have better english than mine), we can have beatiful documentation with motivation behind design in it, based on this two examples.

**Comment by Mortal** [comment]
I've given the docs a bit more work, and I'm happier now with how it's turned out.

**Comment by warsaw** [comment]
@Mortal Thanks for this.  I hope you don't mind me taking a crack at reorganizing this a bit.

**Comment by Mortal** [comment]
By all means go ahead - let's get the docs in the best shape possible for 1.0.

**Comment by Mortal** [comment]
@warsaw I'm currently writing a page on migrating from smtpd to aiosmtpd -- should I put that into this PR or open a separate PR?

**Comment by warsaw** [comment]
On May 10, 2017, at 08:01 PM, Mathias Rav wrote:

>@warsaw I'm currently writing a page on migrating from smtpd to aiosmtpd --
>should I put that into this PR or open a separate PR?

That would be very useful!  Can you put it in a separate PR?

**Comment by warsaw** [comment]
Closing as this was the base branch for #93 -- Thanks!

**Pull request closed without merging**
