### PR TITLE
fix: Fix the QA job by skipping some checks and fix others.

### PR DESCRIPTION
**Pull request by maxking**
## What do these changes do?

Fixes the QA job by ignoring or fixing new Flake8 checks added by various plugins.

## Are there changes in behavior for the user?

No.

## Related issue number

Related to #277 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] tox testenvs have been executed in the following environments:
  
  - [ ] Linux (Ubuntu 18.04, Ubuntu 20.04, Arch): `{py36,py37,py38,py39}-{nocov,cov,diffcov}, qa, docs`
  - [ ] Windows (7, 10): `{py36,py37,py38,py39}-{nocov,cov,diffcov}`
  - [ ] WSL 1.0 (Ubuntu 18.04): `{py36,py37,py38,py39}-{nocov,cov,diffcov}, pypy3-{nocov,cov}, qa, docs`
  - [ ] FreeBSD (12.2, 12.1, 11.4): `{py36,pypy3}-{nocov,cov,diffcov}, qa`
  - [ ] Cygwin: `py36-{nocov,cov,diffcov}, qa, docs`
- [x] Documentation reflects the changes
- [ ] Add a news fragment into the `NEWS.rst` file
  
  * Add under the "aiosmtpd-next" section, creating one if necessary
    * You may create subsections to group the changes, if you like
  * Use full sentences with correct case and punctuation
  * Refer to relevant Issue if applicable

### CODE REVIEW

**Comment by waynew** [comment]
@maxking looks like there's a typing failure :upside_down_face:

**Comment by maxking** [comment]
There are many typing failures actually (pytype seems to stop after it finds errors in one file), let me see if I can fix them.

**Comment by maxking** [comment]
In my fork, the [QA tests are passing completely](https://github.com/maxking/aiosmtpd/actions/runs/3334336735/jobs/5517187233).

**Comment by waynew** [comment]
OK, kicking off these tests again, let's see if they pass. I'll go ahead and merge this probably tomorrow if nobody has any complaints :+1: that way I can merge the other PRs as well.

**Comment by waynew** [comment]
Since the QA job is passing here, I'm going to go ahead and merge to unblock the other PRs

**Comment by maxking** [comment]
Thanks @waynew!

**Pull request merged**
