### PR TITLE
Fix #78 by removing error on duplicate greetings.

### LINKED ISSUE #78: Duplicated HELO/EHLO
As already mentioned in source code (https://github.com/aio-libs/aiosmtpd/blob/c25b878473b086150d32fcd21c35c58099947e5f/aiosmtpd/smtp.py#L264, also in original smtpd's code) a second HELO/EHLO is rejected but the standart says it should be handled as a RSET command.

Is there any special reason to not allow duplicated HELO/EHLO?  I think the best way is to do the same other SMTP servers do: Allowing a duplicated HELO/EHLO.
Another option is to have a configuration option.

### PR DESCRIPTION
**Pull request by zvyn**
See http://bugs.python.org/issue21783 for initial report and discussion
of this issue.

### CODE REVIEW

**Comment by zvyn** [comment]
Resolves #78 (github didn't pick that up for some reason).

**Comment by warsaw** [comment]
Thanks!  This generally looks pretty good, but I'd like to see a little more elaboration on the test changes.  Since duplicate HELO/EHLOs are semantically equivalent to a RSET followed by a HELO/EHLO, can you add a test for that case?

Probably something like:

* Issue a HELO (and a similar case for EHLO, but I don't think we need all combinations thereof)
* Issue a MAIL FROM
* Issue a second HELO
* Complete the full dialog sequence with a *different* MAIL FROM
* Test that the first envelope sender is not in the list, but the second one is.

**Comment by zvyn** [comment]
Done! I couldn't find any similar test cases so I added a new handler to access the envelope independently of the `DATA` command (by using `VRFY`).

**Comment by warsaw** [comment]
Thanks!  This generally looks great, and thanks for the additional tests.  I made a few cleanups and added a NEWS file in #108 .  When that passes CI I'll merge it without squashing so you still get credit for the great work.  Usually I would give you a chance to fix them in your own branch, but due to time constraints on my side, I just went ahead and added a commit on top of your branch.  Hope that's okay!

**Pull request merged**
