### PR TITLE
Refactor SMTP.command_size_limits

### PR DESCRIPTION
**Pull request by Mortal**
Turn the class variable SMTP.command_size_limits into an instance variable named _command_size_limits, initialized with the new method SMTP.get_esmtp_command_size_limits. The _command_size_limits defaultdict is accessed through the new method SMTP.get_command_size_limit.

### CODE REVIEW

**Comment by warsaw** [comment]
In the interest of getting 1.0 out before Pycon, and because this branch has conflicts, I'm deferring it past 1.0

**Comment by waynew** [comment]
@Mortal are you interested in completing this PR?

**Comment by Mortal** [comment]
I'll try to have a look at this on Tuesday.

**Comment by waynew** [comment]
@Mortal any desire to keep working on this or should I add the [help-wanted] tag?

**Comment by Mortal** [comment]
[help-wanted] is probably the best way forward.

**Comment by pepoluan** [comment]
I want to pick this up, but master has diverged so much from this PR I'd rather start over.

But first, a question: Aside from the [size changes for MAIL FROM in RFC1870](https://tools.ietf.org/html/rfc1870#section-3), is there any particular reason why we have to implement some complex mechanism to get the values? What are we aiming for?

**Comment by pepoluan** [comment]
It has been one calendar month since my question, and I don't see any activity to this PR.

I'm going to close this PR for the time being.

Feel free to reopen if anyone thinks this PR should move forward. It's getting waay out-of-sync with `master`, though; might be better to start over with a new PR.

**Pull request closed without merging**
