### PR TITLE
Fixed STARTTLS with uvloop

### PR DESCRIPTION
**Pull request by kasimov-maxim**
## What do these changes do?
After created an SSL context to support STARTTLS command, tried to run command:
`openssl s_client -starttls smtp -crlf  -connect localhost:8025`

it raises:
`
Traceback (most recent call last):
  File "/.../lib/python3.10/site-packages/aiosmtpd/smtp.py", line 741, in _handle_client
    await method(arg)
  File "/.../lib/python3.10/site-packages/aiosmtpd/smtp.py", line 901, in smtp_STARTTLS
    self._original_transport._protocol = self._tls_protocol
AttributeError: 'uvloop.loop.TCPTransport' object has no attribute '_protocol'
`

- **uvloop version**: 0.16.0
- **python version**: 3.10
- **platform**: Linux Mint 20.2

Since the minimal python version is 3.6 and `set_protocol()` was added in python 3.5, the above method was used to fix the error.

## Are there changes in behavior for the user?
No user-visible changes made.

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] tox testenvs have been executed in the following environments:
  
  - [x] Linux (Ubuntu 18.04, Ubuntu 20.04, Arch): `{py36,py37,py38,py39}-{nocov,cov,diffcov}, qa, docs`
  - [ ] Windows (7, 10): `{py36,py37,py38,py39}-{nocov,cov,diffcov}`
  - [ ] WSL 1.0 (Ubuntu 18.04): `{py36,py37,py38,py39}-{nocov,cov,diffcov}, pypy3-{nocov,cov}, qa, docs`
  - [ ] FreeBSD (12.2, 12.1, 11.4): `{py36,pypy3}-{nocov,cov,diffcov}, qa`
  - [ ] Cygwin: `py36-{nocov,cov,diffcov}, qa, docs`
- [ ] Documentation reflects the changes
- [ ] Add a news fragment into the `NEWS.rst` file
  
  * Add under the "aiosmtpd-next" section, creating one if necessary
    * You may create subsections to group the changes, if you like
  * Use full sentences with correct case and punctuation
  * Refer to relevant Issue if applicable

### CODE REVIEW

**Comment by waynew** [comment]
I used the following script:

```
import asyncio
import uvloop
import aiosmtpd
import aiosmtpd.main
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

aiosmtpd.main.main()
```

I ran it with 

```
python fun.py --tlscert test.crt --tlskey test.key -n -d  -l localhost:9999
```

Then I ran 

```
openssl s_client -starttls smtp -crlf -connect localhost:9999
```

Against the current master branch, in fails with the reported error, and with this change it does not blow up :+1: 

That being said, it looks like the qa_docs is failing :eyes:

**Comment by waynew** [comment]
@kasimov-maxim are you able to look into this failing build? I'd like to get this stuff merged in over the next week or two.

**Comment by pepoluan** [comment]
Closing & reopening to trigger GHCI.

**Comment by pepoluan** [comment]
If the tests are all green, I'd like to merge this to 1.4.3 as well, rather than delaying to 1.5.0.

After all, the changes are minimal (just 1 line of code), does not change any logic, but rather adds compatibility with `uvloop` which is something quite important.

**Comment by pepoluan** [comment]
Is all green! Squamerging now.

**Pull request merged**
